// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr5_pnyoxRyOb-RROsKwfpq4RCk6yNc3Q',
    appId: '1:486523941614:web:0d7d5d16f7c79fa0bbf9ff',
    messagingSenderId: '486523941614',
    projectId: 'course-hotelio-e2cea',
    authDomain: 'course-hotelio-e2cea.firebaseapp.com',
    storageBucket: 'course-hotelio-e2cea.appspot.com',
    measurementId: 'G-GPZTJWK7NQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrUOqf0cDn568fQH8Es9nU861slhfNzqs',
    appId: '1:486523941614:android:5153fb568858a84bbbf9ff',
    messagingSenderId: '486523941614',
    projectId: 'course-hotelio-e2cea',
    storageBucket: 'course-hotelio-e2cea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCehW3LSv_4ako_K-IO8atZOP8GkaK85mY',
    appId: '1:486523941614:ios:eb971631ec88a722bbf9ff',
    messagingSenderId: '486523941614',
    projectId: 'course-hotelio-e2cea',
    storageBucket: 'course-hotelio-e2cea.appspot.com',
    iosBundleId: 'com.example.courseHotelio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCehW3LSv_4ako_K-IO8atZOP8GkaK85mY',
    appId: '1:486523941614:ios:2e7eef2831e298e7bbf9ff',
    messagingSenderId: '486523941614',
    projectId: 'course-hotelio-e2cea',
    storageBucket: 'course-hotelio-e2cea.appspot.com',
    iosBundleId: 'com.example.courseHotelio.RunnerTests',
  );
}
